<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class RekamMedis extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_form_model');
    }

    public function index()
    {
        $cara_masuk_url = $this->uri->segment(3);
        if($cara_masuk_url=='walan'){
            $cara_masuk ="RAWAT JALAN";
        }elseif($cara_masuk_url=='wanap'){
            $cara_masuk ="RAWAT INAP";
        
        }else{
             $cara_masuk ="RAWAT INAP";
        }

        $data['form_data'] = $this->Tbl_form_model->get_data_pendaftaran($cara_masuk);

        $this->template->load('template','rekam_medis/list_pendaftaran', $data);
    } 

    function detail_rekam_medis(){
        $no_rawat = substr($this->uri->uri_string(3),30);



         $sql_daftar = "SELECT pd.no_rekamedis,pd.no_rawat,ps.nama_pasien FROM 
                        tbl_pendaftaran as pd,tbl_pasien as ps
                        WHERE pd.no_rekamedis=ps.no_rekamedis and pd.no_rawat='$no_rawat'"; 
        
        $sql_tindakan = "SELECT a.id_riwayat_tindakan, b.nama_tindakan, a.hasil_periksa, a.perkembangan, c.keterangan, a.tanggal, COUNT(*) jumlah_pemeriksa  FROM tbl_riwayat_tindakan a JOIN tbl_tindakan b ON a.id_tindakan = b.id_tindakan
        JOIN tbl_pj_riwayat_tindakan c ON a.id_riwayat_tindakan = c.id_riwayat_tindakan WHERE no_rawat='$no_rawat'
        GROUP BY a.id_riwayat_tindakan";

        $sql_obat = "SELECT a.id_obat_alkes_bhp AS 'id_obat', b.nama_barang AS 'nama_obat', jumlah, tanggal FROM tbl_riwayat_pemberian_obat a 
        JOIN tbl_obat_alkes_bhp b ON a.id_obat_alkes_bhp = b.id_obat_alkes_bhp WHERE no_rawat='$no_rawat'";

        $sql_pemeriksaan_laboratorium = "SELECT b.nama_periksa, hasil, keterangan, tanggal FROM tbl_riwayat_pemeriksaan_laboratorium a
        JOIN tbl_pemeriksaan_laboratorium b ON a.id_pemeriksaan_laboratorium = b.id_pemeriksaan_laboratorium WHERE no_rawat='$no_rawat'";

        $sql_diagnosa_penyakit = "SELECT nama_penyakit, a.ciri_ciri_penyakit, a.ciri_ciri_umum, a.keterangan, tanggal FROM tbl_riwayat_diagnosa_penyakit a
        JOIN tbl_diagnosa_penyakit b ON a.id_diagnosa_penyakit = b.id_diagnosa_penyakit WHERE no_rawat='$no_rawat'";
        

        $data['form']=  $this->db->query($sql_daftar)->row_array();
        $data['no_rawat'] = $no_rawat;
        //GET DATA
        $data['tindakan']                   = $this->db->query($sql_tindakan)->result();
        $data['pemberian_obat']             = $this->db->query($sql_obat)->result();
        $data['pemeriksaan_laboratorium']   = $this->db->query($sql_pemeriksaan_laboratorium)->result();
        $data['riwayat_diagnosa_penyakit']          = $this->db->query($sql_diagnosa_penyakit)->result();


        $data['diagnosa_penyakit']          = $this->db->get('tbl_diagnosa_penyakit')->result();


        $this->template->load('template','rekam_medis/detail_rekam_medis',$data);
    }

}

/* End of file Spesialis.php */
/* Location: ./application/controllers/Spesialis.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-22 07:41:07 */
/* http://harviacode.com */