<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_prakter_dokter_model extends CI_Model
{

    public $table = 'tbl_jadwal_prakter_dokter';
    public $id = 'id_jadwal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_jadwal,nama_dokter,hari,jam_mulai,ja_selesai,nama_poliklinik');
        $this->datatables->from('tbl_jadwal_prakter_dokter');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_jadwal_prakter_dokter.field = table2.field');

        $this->datatables->join('tbl_dokter', 'tbl_jadwal_prakter_dokter.kode_dokter = tbl_dokter.kode_dokter');
        $this->datatables->join('tbl_poliklinik', 'tbl_jadwal_prakter_dokter.id_poliklinik = tbl_poliklinik.id_poliklinik');
        $this->datatables->add_column('action', anchor(site_url('praktekdokter/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('praktekdokter/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_jadwal');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('kode_dokter', $q);
	$this->db->or_like('hari', $q);
	$this->db->or_like('jam_mulai', $q);
	$this->db->or_like('ja_selesai', $q);
	$this->db->or_like('id_poliklinik', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('kode_dokter', $q);
	$this->db->or_like('hari', $q);
	$this->db->or_like('jam_mulai', $q);
	$this->db->or_like('ja_selesai', $q);
	$this->db->or_like('id_poliklinik', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_prakter_dokter_model.php */
/* Location: ./application/models/Tbl_prakter_dokter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-17 07:29:51 */
/* http://harviacode.com */