<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_input_inap_model extends CI_Model
{

    public $table = 'tbl_pemeriksaan_rawat_inap';
    public $id = 'id_periksa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_periksa', $q);
	$this->db->or_like('no_rawat', $q);
	$this->db->or_like('no_rekamedis', $q);
	$this->db->or_like('nama_pasien', $q);
	$this->db->or_like('tanggal_daftar', $q);
	$this->db->or_like('id_tempat_tidur', $q);
	$this->db->or_like('id_obat', $q);
	$this->db->or_like('id_tindakan', $q);
	$this->db->or_like('id_pemeriksaan_laboratorium', $q);
	$this->db->or_like('id_diagnosa_penyakit', $q);
	$this->db->or_like('Hasil_pemeriksaan_fisik', $q);
	$this->db->or_like('riwayat_penyakit', $q);
	$this->db->or_like('keluhan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_periksa', $q);
	$this->db->or_like('no_rawat', $q);
	$this->db->or_like('no_rekamedis', $q);
	$this->db->or_like('nama_pasien', $q);
	$this->db->or_like('tanggal_daftar', $q);
	$this->db->or_like('id_tempat_tidur', $q);
	$this->db->or_like('id_obat', $q);
	$this->db->or_like('id_tindakan', $q);
	$this->db->or_like('id_pemeriksaan_laboratorium', $q);
	$this->db->or_like('id_diagnosa_penyakit', $q);
	$this->db->or_like('Hasil_pemeriksaan_fisik', $q);
	$this->db->or_like('riwayat_penyakit', $q);
	$this->db->or_like('keluhan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_input_inap_model.php */
/* Location: ./application/models/Tbl_input_inap_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-05 08:49:09 */
/* http://harviacode.com */